### ISSUE TITLE
ModuleNotFoundError: No module named 'dognet.data.syntetic

### ISSUE THREAD

**Issue by nellyyi** [kulikovv/dognet#1]
Trying to execute any ipython notebook or directly in run directory elicits a ModuleNotFound error:

I can't see any file within the dognet/data directory that would contain the class SynapseSignalModel,SynapseType,SynapseType2, neither could I find them anywhere in the directory.

Background:
Working on a Mac 10.14. Cloned the directory, executed the setup.py; jupyter notebook weiler14.ipynb,  and then tried to run the first cell which causes an module import error. 
 (seem to have no other module problems, everything else imports well). 

```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-663fe1295518> in <module>()
     10 from matplotlib_scalebar.scalebar import ScaleBar
     11 from skimage.transform import rescale
---> 12 import dognet
     13 from sklearn.metrics import roc_curve, auc

~/Alla/DoGNet/dognet/dognet/__init__.py in <module>()
     38 
     39 from .baselines import *
---> 40 from .data import *

~/Alla/DoGNet/dognet/dognet/data/__init__.py in <module>()
      6 from .collman import Collman
      7 from .weiler import Weiler
----> 8 from .syntetic import SynapseSignalModel,SynapseType,SynapseType2

ModuleNotFoundError: No module named 'dognet.data.syntetic


```

**Comment by kulikovv** [comment]
Thank you,
Bug fixed, please pull the update from the repository.
